<a href="https://colab.research.google.com/github/SuryARavichan/numpy_bas_ope/blob/main/numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import random


In [6]:
list_1 = [1,2,3,4,5]
np.arr_1 = np.array(list_1,dtype=np.int8)
np.arr_1



array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]])

In [8]:
m_list_1 = [[1,2,3,4,5],[7,8,9,10,11]]
np_m_arr_1 = np.array(m_list_1)
np_m_arr_1

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]])

In [11]:
np.arange(0,15)
np.linspace(2,15,3)

array([ 2. ,  8.5, 15. ])

In [12]:
np.linspace(2,15,3)

array([ 2. ,  8.5, 15. ])

In [13]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.zeros(4)

array([0., 0., 0., 0.])

In [16]:
np_arr_2 = np.array([2,4,6,8,10])
np_arr_2.dtype

dtype('int64')

In [18]:
np.random.randint(15,23, size=(2,5))


array([[17, 22, 21, 21, 17],
       [19, 19, 17, 21, 15]])

In [21]:
np_m_arr_1[0,0] = 2
np_m_arr_1.itemset(1,2)
np_m_arr_1


array([[ 2,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]])

In [27]:
np_m_arr_1[0:5]


array([[ 2,  2, 15,  4,  5],
       [ 7,  8,  9, 96, 32]])

In [29]:
evens = np_m_arr_1[np_m_arr_1 %2==0]
evens

array([ 2,  2,  4,  8, 96, 32])

In [31]:
greater = np_m_arr_1[np_m_arr_1 > 5]
greater

array([15,  7,  8,  9, 96, 32])

In [36]:
np_m_arr_1.transpose()


array([[ 2,  7],
       [ 2,  8],
       [15,  9],
       [ 4, 96],
       [ 5, 32]])

In [40]:
np_m_arr_1.flatten()

array([ 2,  2, 15,  4,  5,  7,  8,  9, 96, 32])

In [52]:
cp_arr_1 = np.random.randint(10, size=(2,3))
cp_arr_2 = cp_arr_1
cp_arr_1[0,0] = 2
print('cp_arr_1\n',cp_arr_1)
print('cp_arr_2\n',cp_arr_2)
cp_arr_3 = cp_arr_1.view()
cp_arr_3.flatten('F')
cp_arr_3

cp_arr_1
 [[2 0 4]
 [1 9 4]]
cp_arr_2
 [[2 0 4]
 [1 9 4]]


array([[2, 0, 4],
       [1, 9, 4]])

In [56]:
arr_3 = np.array([1,2,3,4,15])
arr_4 = np.array([2,4,6,8,10])
print(arr_3 + arr_4)
print(arr_3 - arr_4)
print(arr_3 * arr_4)
print(arr_3 / arr_4)


[ 3  6  9 12 25]
[-1 -2 -3 -4  5]
[  2   8  18  32 150]
[0.5 0.5 0.5 0.5 1.5]


In [60]:
arr_5 = np.random.randint(120, size=(2,3))
arr_5



array([[ 25, 135, 131,  72,  93],
       [100, 149, 145,  68,  69],
       [128, 103, 134,  18,  67]])

In [61]:
arr_6 = np.random.randint(150, size=(3,5))
arr_6

array([[ 97,  30, 146,  64,  28],
       [ 45,  52,  97, 137, 123],
       [ 97,  85,  88,  14,  29]])

In [63]:
arr_3.sum()

25

In [65]:
arr_5.sum()


232

In [67]:
arr_6.cumsum()


array([  97,  127,  273,  337,  365,  410,  462,  559,  696,  819,  916,
       1001, 1089, 1103, 1132])

In [69]:
arr_4.conjugate()


array([ 2,  4,  6,  8, 10])

In [71]:
print(arr_5.mean())
print(arr_5.min())
print(arr_5.max())

38.666666666666664
8
73


In [75]:
print(np.sqrt(arr_6))
print(np.cbrt(arr_4))
print(np.exp(arr_5))
print(np.log(arr_3))


[[ 9.8488578   5.47722558 12.08304597  8.          5.29150262]
 [ 6.70820393  7.21110255  9.8488578  11.70469991 11.09053651]
 [ 9.8488578   9.21954446  9.38083152  3.74165739  5.38516481]]
[1.25992105 1.58740105 1.81712059 2.         2.15443469]
[[5.83461743e+14 6.56599691e+07 1.14200739e+26]
 [2.98095799e+03 8.65934004e+16 5.05239363e+31]]
[0.         0.69314718 1.09861229 1.38629436 2.7080502 ]


In [77]:
np.lcm.reduce([9,12,15])

180

In [79]:
np.floor([9,15,30])

array([ 9., 15., 30.])

In [80]:
np.ceil([12,30])



array([12., 30.])