<a href="https://colab.research.google.com/github/SuryARavichan/numpy_bas_ope/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [5]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [8]:
a = np.zeros(15)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
a.shape

(15,)

In [14]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [18]:
a = np.empty(2)
a

array([4.68380674e-310, 6.90526964e-310])

In [20]:
a = np.linspace(2,5,8)
a

array([2.        , 2.42857143, 2.85714286, 3.28571429, 3.71428571,
       4.14285714, 4.57142857, 5.        ])

In [23]:
type(a)

numpy.ndarray

In [26]:
a = np.arange(4,10)
a

array([4, 5, 6, 7, 8, 9])

In [39]:
a = np.random.random_integers(4,50)
a

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(4, 50 + 1) instead
  """Entry point for launching an IPython kernel.


28